timezones:
  - "Pacific/Kiritimati"
  - "Pacific/Auckland"
  - "Pacific/Noumea"
  - "Australia/Sydney"
  - "Asia/Tokyo"
  - "Asia/Hong_Kong"
  - "Asia/Bangkok"
  - "Asia/Dhaka"
  - "Asia/Kathmandu"
  - "Asia/Kolkata"
  - "Asia/Kabul"
  - "Europe/Moscow"
  - "Europe/Bucharest"
  - "Europe/Madrid"
  - "Europe/London"
  - "UTC"
  - "Atlantic/Cape_Verde"
  - "America/Noronha"
  - "America/Sao_Paulo"
  - "America/New_York"
  - "America/Chicago"
  - "America/Denver"
  - "America/Phoenix"
  - "America/Los_Angeles"
  - "America/Anchorage"
  - "America/Adak"
  - "Pacific/Honolulu"
  - "Pacific/Samoa"
color:
  current: "Asia/Tokyo"
  important:
    - "America/Los_Angeles"
    - "Europe/London"
