static const char *embedded_zones[] = {
      "Pacific/Kiritimati",
      "Pacific/Auckland",
      "Pacific/Noumea",
      "Australia/Sydney",
      "Asia/Tokyo",
      "Asia/Hong_Kong",
      "Asia/Bangkok",
      "Asia/Dhaka",
      "Asia/Kathmandu",
      "Asia/Calcutta",
      "Asia/Kabul",
      "Europe/Moscow",
      "Europe/Bucharest",
      "Europe/Madrid",
      "Europe/London",
      "UTC",
      "Atlantic/Cape_Verde",
      "America/Noronha",
      "America/Sao_Paulo",
      "America/New_York",
      "America/Chicago",
      "America/Denver",
      "America/Phoenix",
      "America/Los_Angeles",
      "America/Anchorage",
      "America/Adak",
      "Pacific/Honolulu",
      "Pacific/Samoa",
};
static const int num_embedded_zones = 28;
static const char *current_zone = "Asia/Tokyo";
static const char *important_zones[] = {
      "America/Los_Angeles",
      "Europe/London",
};
static const int num_important_zones = 2;
